name: MyPlugins
version: 1.0
author: Kyanoe
main: me.myPlugin.kano.plugin.Main
api-version: 1.13
commands:
  give:
    description: give other player an item.
    usage: /<command>
  fly:
    description: enable or disable fly.
    usage: /<command>
  help:
    description: list commands for this plugin.
    usage: /<command>
  heal:
    description: heal other player
    usage: /<command>
  feed:
    description: feed other player
    usage: /<command>
  spawnmob:
    description: spawn a mob at your location.
    usage: /<command>
  gmsp:
    description: change your gamemode to spectator.
    usage: /<command>
  gmc:
    description: change your gamemode to creative.
    usage: /<command>
  gms:
    description: change your gamemode to survival.
    usage: /<command>